@api_url = http://localhost:9000/api/v1
### Sign up 
POST {{api_url}}/auth/signup
Content-Type: application/json

{
  "name":"sagar",
  "email" : "sagar@email.com",
  "password": "ss",
  "confirmPassword": "ss"
}

### login
POST {{api_url}}/auth/login
Content-Type: application/json

{
  "email" : "sagar@email.com",
  "password": "ss"
}

### Create transactions 
POST {{api_url}}/transactions/transaction
Content-Type: application/json

{
  "title":"salary",
  "income":1000,
  "createdAt": "2024-10-13"
}

### Get all transactions 
GET  {{api_url}}/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzRhZWE1YmVhYmVhODc0YThmZDdmZTkiLCJlbWFpbCI6InNhZ2FyQGVtYWlsLmNvbSIsImlhdCI6MTczMjk2MzE1OSwiZXhwIjoxNzMzMDQ5NTU5fQ.TIbzXk8l1gVTlc-leCUMpQkVR3C4IaHLdBGHlhi1W1M

Content-Type: application/json


### Get transaction by id 
GET  {{api_url}}/transactions/672dd76e7c07cb931486df47
Content-Type: application/json


### Delete Transaction 
DELETE  {{api_url}}/transactions/672dd76e7c07cb931486df47
Content-Type: application/json


### Update Transaction 
@transaction_id = 
PATCH {{api_url}}/transactions/{{transaction_id}}
Content-Type: application/json

{
  "title": "updated"
}