@api_url = http://localhost:9000/api/v1
### Sign up 
POST {{api_url}}/auth/signup
Content-Type: application/json

{
  "name":"sagar",
  "email" : "mailtosagarpoudel@gmail.com",
  "password": "ss",
  "confirmPassword": "ss"
}

### login
POST {{api_url}}/auth/login
Content-Type: application/json

{
  "email" : "mailtosagarpoudel@gmail.com",
  "password": "ss"
}

### Create transactions 
POST {{api_url}}/transactions/transaction
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M2NmJjODNkMDMxZTQ3YjhmMTFhMjYiLCJlbWFpbCI6InNhZ2FyQHRlc3QuY29tIiwibmFtZSI6IlNhZ2FyIiwiaWF0IjoxNzQxMTM3NzEyLCJleHAiOjE3NDEyMjQxMTJ9.xPIyq2Zw0wgzeCPE_YJo07gy03km1iA9BJozNcVGB0Q
Content-Type: application/json

{
  
  "title": "salary",
  "income":1000,
  "createdAt": "2024-10-13"
}

### Get all transactions 
GET  {{api_url}}/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M2NmJjODNkMDMxZTQ3YjhmMTFhMjYiLCJlbWFpbCI6InNhZ2FyQHRlc3QuY29tIiwibmFtZSI6IlNhZ2FyIiwiaWF0IjoxNzQxMTM3NzEyLCJleHAiOjE3NDEyMjQxMTJ9.xPIyq2Zw0wgzeCPE_YJo07gy03km1iA9BJozNcVGB0Q
Content-Type: application/json


### Get transaction by id 
POST  {{api_url}}/transactions/67c7ac69af9b3b41d2f03e72
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M2NmJjODNkMDMxZTQ3YjhmMTFhMjYiLCJlbWFpbCI6InNhZ2FyQHRlc3QuY29tIiwibmFtZSI6IlNhZ2FyIiwiaWF0IjoxNzQxMTM3NzEyLCJleHAiOjE3NDEyMjQxMTJ9.xPIyq2Zw0wgzeCPE_YJo07gy03km1iA9BJozNcVGB0Q
Content-Type: application/json


### Delete Transaction 
DELETE  {{api_url}}/transactions/67c7ac69af9b3b41d2f03e72
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M2NmJjODNkMDMxZTQ3YjhmMTFhMjYiLCJlbWFpbCI6InNhZ2FyQHRlc3QuY29tIiwibmFtZSI6IlNhZ2FyIiwiaWF0IjoxNzQxMTM3NzEyLCJleHAiOjE3NDEyMjQxMTJ9.xPIyq2Zw0wgzeCPE_YJo07gy03km1iA9BJozNcVGB0Q
Content-Type: application/json


### Update Transaction 
@transaction_id = 67c7ac8baf9b3b41d2f03e74
PATCH {{api_url}}/transactions/{{transaction_id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M2NmJjODNkMDMxZTQ3YjhmMTFhMjYiLCJlbWFpbCI6InNhZ2FyQHRlc3QuY29tIiwibmFtZSI6IlNhZ2FyIiwiaWF0IjoxNzQxMTM3NzEyLCJleHAiOjE3NDEyMjQxMTJ9.xPIyq2Zw0wgzeCPE_YJo07gy03km1iA9BJozNcVGB0Q
Content-Type: application/json

{
  "title": "updated"
}

###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Q0YTk0MmNmYzg2MDgzYzkzOWYwNmIiLCJlbWFpbCI6Im1haWx0b3NhZ2FycG91ZGVsQGdtYWlsLmNvbSIsIm5hbWUiOiJzYWdhciIsImlhdCI6MTc0MTk5MDIxMCwiZXhwIjoxNzQyMjQ5NDEwfQ.Q4vE82mNJ5FT3XmZquM7OBKUHDFh3lCsLhjORhxJQ-w
GET  http://localhost:9000/api/v1/auth/useremailverification/{{token}}
Content-Type: application/json