@api_url = http://financetrackerbe-env.eba-gti8bw6i.ap-southeast-2.elasticbeanstalk.com/api/v1

### Sign up 
POST {{api_url}}/auth/signup
Content-Type: application/json

{
  "name":"new",
  "email" : "aws@email.com",
  "password": "ss",
  "confirmPassword": "ss"
}

### login
POST {{api_url}}/auth/login
Content-Type: application/json

{
  "email" : "sagar@email.com",
  "password": "ss"
}

### Create transactions 
POST {{api_url}}/transactions/transaction
Authorization: Bearer 
Content-Type: application/json

{
  "title":"salary",
  "income":1000,
  "createdAt": "2024-10-13"
}

### Get all transactions 
GET  {{api_url}}/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzRhZWE1YmVhYmVhODc0YThmZDdmZTkiLCJlbWFpbCI6InNhZ2FyQGVtYWlsLmNvbSIsIm5hbWUiOiJzYWdhciIsImlhdCI6MTczMzU2MzIxNiwiZXhwIjoxNzMzNjQ5NjE2fQ.M-4gbV3Ao0wQI5jhB2PcZU9EJFQR-KtcKmLCumtQaXo
Content-Type: application/json


### Get transaction by id 
POST  {{api_url}}/transactions/672de7eb22de7c1125b86a77
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzRhZWE1YmVhYmVhODc0YThmZDdmZTkiLCJlbWFpbCI6InNhZ2FyQGVtYWlsLmNvbSIsImlhdCI6MTczMzQ3MzEyMiwiZXhwIjoxNzMzNTU5NTIyfQ.xRmyq3S3zeAxt7Cmnw0IB61AEf2VFODmMeneXJkjo80

Content-Type: application/json


### Delete Transaction 
DELETE  {{api_url}}/transactions/672dd76e7c07cb931486df47
Content-Type: application/json


### Update Transaction 
@transaction_id = 672de7eb22de7c1125b86a73
PATCH {{api_url}}/transactions/{{transaction_id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzRhZWE1YmVhYmVhODc0YThmZDdmZTkiLCJlbWFpbCI6InNhZ2FyQGVtYWlsLmNvbSIsImlhdCI6MTczMzQ3MzEyMiwiZXhwIjoxNzMzNTU5NTIyfQ.xRmyq3S3zeAxt7Cmnw0IB61AEf2VFODmMeneXJkjo80
Content-Type: application/json

{
  "title": "updated"
}